export default {
  login: 'binhstatic',
  id: 65479519,
  node_id: 'MDQ6VXNlcjY1NDc5NTE5',
  avatar_url: 'https://avatars.githubusercontent.com/u/65479519?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/binhstatic',
  html_url: 'https://github.com/binhstatic',
  followers_url: 'https://api.github.com/users/binhstatic/followers',
  following_url:
    'https://api.github.com/users/binhstatic/following{/other_user}',
  gists_url: 'https://api.github.com/users/binhstatic/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/binhstatic/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/binhstatic/subscriptions',
  organizations_url: 'https://api.github.com/users/binhstatic/orgs',
  repos_url: 'https://api.github.com/users/binhstatic/repos',
  events_url: 'https://api.github.com/users/binhstatic/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/binhstatic/received_events',
  type: 'User',
  site_admin: false,
  name: 'Văn Bình',
  company: '@manabie-com',
  blog: 'binf.netlify.app',
  location: 'Hồ Chí Minh, Việt Nam',
  email: null,
  hireable: null,
  bio: 'Hello',
  twitter_username: 'binfgau',
  public_repos: 43,
  public_gists: 1,
  followers: 4,
  following: 5,
  created_at: '2020-05-17T04:45:43Z',
  updated_at: '2023-03-08T08:11:55Z',
};
